In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn.metrics as classification
from sklearn import metrics
from sklearn import tree

In [2]:
import pandas as pd
df=pd.read_csv('basic.csv')

In [3]:
df.head()

,Unnamed: 0,State,District,Variety,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
0,0,Kerala,Kottayam,Potato,19/08/2024,4400,4600,4500
1,1,Kerala,Kottayam,Onion,19/08/2024,7500,8600,8000
2,2,Kerala,Malappuram,Tea,19/08/2024,11500,11600,11550
3,3,Madhya Pradesh,Ujjain,Atta,19/08/2024,2200,2200,2200
4,4,Manipur,Bishnupur,Masur,19/08/2024,9500,10000,9750

In [4]:
df = df.drop(['Unnamed: 0', 'Arrival_Date'], axis=1)

In [5]:
df

,State,District,Variety,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
0,Kerala,Kottayam,Potato,4400,4600,4500
1,Kerala,Kottayam,Onion,7500,8600,8000
2,Kerala,Malappuram,Tea,11500,11600,11550
3,Madhya Pradesh,Ujjain,Atta,2200,2200,2200
4,Manipur,Bishnupur,Masur,9500,10000,9750
...,...,...,...,...,...,...
140,West Bengal,Bankura,Vanaspati oil,3400,3600,3500
141,West Bengal,Bankura,Vanaspati oil,3550,3700,3600
142,West Bengal,Birbhum,Vanaspati oil,3350,3450,3400
143,West Bengal,Jalpaiguri,Tomato,4300,4500,4400
144,West Bengal,Murshidabad,Soya oil,3530,3570,3555

In [6]:
X = df.iloc[:, :-1]
y = df['Modal_x0020_Price']
X

,State,District,Variety,Min_x0020_Price,Max_x0020_Price
0,Kerala,Kottayam,Potato,4400,4600
1,Kerala,Kottayam,Onion,7500,8600
2,Kerala,Malappuram,Tea,11500,11600
3,Madhya Pradesh,Ujjain,Atta,2200,2200
4,Manipur,Bishnupur,Masur,9500,10000
...,...,...,...,...,...
140,West Bengal,Bankura,Vanaspati oil,3400,3600
141,West Bengal,Bankura,Vanaspati oil,3550,3700
142,West Bengal,Birbhum,Vanaspati oil,3350,3450
143,West Bengal,Jalpaiguri,Tomato,4300,4500
144,West Bengal,Murshidabad,Soya oil,3530,3570

In [7]:
X=X.values

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=0, shuffle=True)

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
ohe = OneHotEncoder(drop='first',sparse_output=False,handle_unknown='ignore')
scale = StandardScaler()

preprocesser = ColumnTransformer(
        transformers = [
            ('StandardScale', scale,[3,4] ),
            ('OHE', ohe, [0,1,2]),
        ],
        remainder='passthrough'
)

In [12]:
X_train_dummy = preprocesser.fit_transform(X_train)
X_test_dummy = preprocesser.transform(X_test)

C:\Users\AA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\preprocessing\_encoders.py:241: UserWarning: Found unknown categories in columns [0, 1, 2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [13]:
preprocesser.get_feature_names_out()

array(['StandardScale__x3', 'StandardScale__x4',
       'OHE__x0_Himachal Pradesh', 'OHE__x0_Kerala',
       'OHE__x0_Madhya Pradesh', 'OHE__x0_Manipur', 'OHE__x0_Nagaland',
       'OHE__x0_Tripura', 'OHE__x0_Uttar Pradesh', 'OHE__x0_West Bengal',
       'OHE__x1_Ambedkarnagar', 'OHE__x1_Bankura', 'OHE__x1_Bishnupur',
       'OHE__x1_Darjeeling', 'OHE__x1_Farukhabad', 'OHE__x1_Fatehpur',
       'OHE__x1_Gonda', 'OHE__x1_Imphal East', 'OHE__x1_Jaunpur',
       'OHE__x1_Jhansi', 'OHE__x1_Kakching', 'OHE__x1_Kangra',
       'OHE__x1_Kohima', 'OHE__x1_Kottayam', 'OHE__x1_Lucknow',
       'OHE__x1_Murshidabad', 'OHE__x1_North Tripura',
       'OHE__x1_Prayagraj', 'OHE__x1_Sambhal', 'OHE__x1_Shahjahanpur',
       'OHE__x1_Sitapur', 'OHE__x1_Sonipat', 'OHE__x1_Thoubal',
       'OHE__x2_Groundnut oil', 'OHE__x2_Gur', 'OHE__x2_Masur',
       'OHE__x2_Moong', 'OHE__x2_Onion', 'OHE__x2_Potato',
       'OHE__x2_Soya oil', 'OHE__x2_Sugar', 'OHE__x2_Urad',
       'OHE__x2_Vanaspati oil'], dtype=object)

In [14]:
#linear regression
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error,r2_score


models = {
    'lr':LinearRegression(),
    'lss':Lasso(),
    'Rid':Ridge(),
    'Dtr':DecisionTreeRegressor()
}
for name, md in models.items():
    md.fit(X_train_dummy,y_train)
    y_pred = md.predict(X_test_dummy)
    
    print(f"{name} : mae : {mean_absolute_error(y_test,y_pred)} score : {r2_score(y_test,y_pred)}")

lr : mae : 74.81080481482527 score : 0.9989554994406045
lss : mae : 72.25571835482313 score : 0.9986688228654977
Rid : mae : 159.1230299321438 score : 0.9960192788328968
Dtr : mae : 409.26724137931035 score : 0.9714065781856961

C:\Users\AA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.884e+04, tolerance: 5.468e+04
  model = cd_fast.enet_coordinate_descent(

In [16]:
lr = LinearRegression()
lr.fit(X_train_dummy,y_train)
lr.predict(X_test)

ValueError: could not convert string to float: 'Manipur'

In [ ]:
def prediction(food_items,season,min_prize,max_prize):
    # Create an array of the input features
    features = np.array([[food_items,season,min_prize,max_prize]], dtype=object)

    # Transform the features using the preprocessor
    transformed_features = preprocesser.transform(features)

    # Make the prediction
    predicted_yield = lr.predict(transformed_features).reshape(1, -1)

    return predicted_yield[0]
result = prediction('Gram','Spring',63.72,86.09)

In [ ]:
result